### ISSUE TITLE
[FR] Image to Skin

### ISSUE THREAD

**Issue by mpena211** [bs-community/skinview3d#106]
Are there any plans to implement the ability to put in an image and convert it to a skin?

**Comment by Hacksore** [comment]
@mpena211 Could you please try to expand on what you mean?

This seems out of scope for the project but I'll let you fill in more supporting information.

**Comment by mpena211** [comment]
@Hacksore Basically, instead of only being able to use skins that are premade, create a method to pass in an image, and make it into the form of a MC skin.

I believe this involves, cropping the image, resizing the image, and then copying portions of it to a blank white image in the specific locations for the skin template.

**Comment by Hacksore** [comment]
@mpena211 This is something you'd really want to do in your application. Here is a crude sandbox that shows you can render a canvas with an arbitrary image.

https://codesandbox.io/s/skinview3d-load-arbitrary-image-tfljn?file=/src/index.js

You'd need to take that a step further and allow custom cropping to get exactly what you desire but this should help you get started.

**Comment by mpena211** [comment]
@Hacksore Gotcha, thanks for the info and the headstart!
