### ISSUE TITLE
NPM version is different from github

### ISSUE THREAD

**Issue by james090500** [bs-community/skinview3d#112]
The version on https://www.npmjs.com/package/skinview3d seems to be missing the loadEars function on this github? Yet version seems to both be 2.2.1. 

Can be seen here if you search for "loadEars" https://unpkg.com/skinview3d@2.2.1/libs/viewer.js

Can we get a new release published?

**Comment by james090500** [comment]
Is there any update for this? Really want to start using the native ear function :(

**Comment by yushijinhun** [comment]
Sorry for the slow response. I've released v2.3.0-alpha.1.
