### ISSUE TITLE
Background Removal when saving image?

### ISSUE THREAD

**Issue by bribes** [bs-community/skinview3d#113]
If you want to save the render as a image that has a transparent background but the skinViewer is FXAA and has a background maybe add a way to switch viewers or remove the background some how? I want the actual render to be FXAA so its nice and smooth but when right clicking and saving the image for the background to be transparent without needing to use photo editing tools. Is there maybe a work around to do? I think in a previous update it was possible to set FXAA background to transparent but that's not longer the case.

**Comment by yushijinhun** [comment]
It seems that three.js now supports transparent background in FXAA (https://github.com/mrdoob/three.js/commit/d4a86dc53fb5057eecae4c9dea46685511e15864).

**Comment by yushijinhun** [comment]
Fixed in https://github.com/bs-community/skinview3d/commit/d702b7ff4d5660aac43af4cbd427cf4010c304f1. You can set the background to transparent using `skinViewer.background = null;`.
