### ISSUE TITLE
Is there a way to make presets for model position?

### ISSUE THREAD

**Issue by megazvezda** [bs-community/skinview3d#120]
Is there a way to make presets for model position, so it appears rotated as I set it?

**Comment by megazvezda** [comment]
still need help

**Comment by megazvezda** [comment]
@Hacksore Not really a pose, but a camera's perspective view on the model

**Comment by Hacksore** [comment]
@megazvezda You have access to move the camera, here is an example.

https://github.com/Hacksore/three-js-extension-icon/blob/primary/src/background/index.js#L23

**Comment by megazvezda** [comment]
Thank you
