### ISSUE TITLE
animation.progress = 0 error

### ISSUE THREAD

**Issue by DmytroDyachkov** [bs-community/skinview3d#124]
Console: https://i.imgur.com/pINIrJd.png

`skin.html:13 Unchecked runtime.lastError: The message port closed before a response was received.
skin.html:13 Unchecked runtime.lastError: The message port closed before a response was received.
skin.html:13 Unchecked runtime.lastError: The message port closed before a response was received.
skin.html:13 Unchecked runtime.lastError: The message port closed before a response was received.
skin.html:1113          GET http://localhost:3000/assets/images/f1.png 404 (Not Found)
skin.html:1117          GET http://localhost:3000/assets/images/f2.png 404 (Not Found)
skin.html:1121          GET http://localhost:3000/assets/images/f3.png 404 (Not Found)
skin.html:1124          GET http://localhost:3000/assets/images/arrow_right_form.svg 404 (Not Found)
viewer.ts:824 Uncaught TypeError: Cannot set properties of undefined (setting 'progress')
    at set animation [as animation] (viewer.ts:824:14)
    at initializeViewer (skinw_init.js:231:26)
    at window.onload (skinw_init.js:251:3)
set animation @ viewer.ts:824
initializeViewer @ skinw_init.js:231
window.onload @ skinw_init.js:251
Объект load (асинхронный)
(анонимная) @ skinw_init.js:1
WebGLProgram.js:804 THREE.WebGLProgram: Program Info Log: C:\fakepath(53,12-96): warning X4713: Sample Bias value is limited to the range [-16.00, 15.99], using -16.000000 instead of -100.000000
C:\fakepath(53,12-96): warning X4713: Sample Bias value is limited to the range [-16.00, 15.99], using -16.000000 instead of -100.000000
C:\fakepath(53,12-96): warning X4713: Sample Bias value is limited to the range [-16.00, 15.99], using -16.000000 instead of -100.000000
C:\fakepath(53,12-96): warning X4713: Sample Bias value is limited to the range [-16.00, 15.99], using -16.000000 instead of -100.000000
C:\fakepath(53,12-96): warning X4713: Sample Bias value is limited to the range [-16.00, 15.99], using -16.000000 instead of -100.000000
C:\fakepath(53,12-96): warning X4713: Sample Bias value is limited to the range [-16.00, 15.99], using -16.000000 instead of -100.000000
C:\fakepath(53,12-96): warning X4713: Sample Bias value is limited to the range [-16.00, 15.99], using -16.000000 instead of -100.000000

 
Br @ WebGLProgram.js:804
acquireProgram @ WebGLPrograms.js:486
Be @ WebGLRenderer.js:1386
(анонимная) @ WebGLRenderer.js:1591
renderBufferDirect @ WebGLRenderer.js:715
Fe @ WebGLRenderer.js:1323
Ue @ WebGLRenderer.js:1292
Oe @ WebGLRenderer.js:1214
render @ WebGLRenderer.js:1034
render @ Pass.js:62
render @ ShaderPass.js:53
render @ EffectComposer.js:141
render @ viewer.ts:651
draw @ viewer.ts:642
(анонимная) @ viewer.ts:417
Объект requestAnimationFrame (асинхронный)
e.SkinViewer @ viewer.ts:417
initializeViewer @ skinw_init.js:217
window.onload @ skinw_init.js:251
Объект load (асинхронный)
(анонимная) @ skinw_init.js:1
`

**Comment by yushijinhun** [comment]
Sorry for the really late reply. Did you set the `animation` property of `SkinViewer` to `undefined`? If you want to cancel the animation, you should set it to `null`.
