### ISSUE TITLE
Using getImageData with the willReadFrequently attribute

### ISSUE THREAD

**Issue by Hacksore** [bs-community/skinview3d#125]
Should we consider allowing the use of `willReadFrequently` to suppress this warning? 

![image](https://user-images.githubusercontent.com/996134/197398237-d7783e78-5148-4d1f-b802-5e87954fd3f3.png)

```
process.js:30 Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently
```

**Comment by bribes** [comment]
Seems good!

**Comment by samzhangjy** [comment]
Any updates on this? I'm currently building a project that includes many `SkinViewer` instances and the warning is really annoying.

**Comment by Hacksore** [comment]
@yushijinhun Could you please have a look at the referenced PR?

**Comment by Hacksore** [comment]
I've opened a PR in the upstream utils repo https://github.com/bs-community/skinview-utils/pull/16. Once we get that merged we can move forward with a fix here.

**Comment by Hacksore** [comment]
Once @yushijinhun publishes a new version we can bump the utils package to close this out.
