### ISSUE TITLE
Disable zoom

### ISSUE THREAD

**Issue by RSNFreud** [bs-community/skinview3d#126]
Is there a way to disable people from zooming in/out? For example set min/max zoom or something

**Comment by Hacksore** [comment]
You can disable it outright with `skinViewer.controls.enableZoom = false`.

On the topic of setting zoom ranges seems that [`maxZoom`](https://threejs.org/docs/#examples/en/controls/OrbitControls.maxZoom)/[`minZoom`](https://threejs.org/docs/#examples/en/controls/OrbitControls.minZoom) are supported with `PerspectiveCamera` but I can't get it to work 😅.

https://codesandbox.io/s/skinview3d-zoom-clamp-4she68?file=/src/index.js

**Comment by Hacksore** [comment]
Oh I reread the docs and it says zoom clamping only works with an `OrthographicCamera` and this library uses a `PerspectiveCamera`.

https://github.com/bs-community/skinview3d/blob/52e1ff69e67a1e123ed637ee82fabc0884608bc1/src/viewer.ts#L314

**Comment by RSNFreud** [comment]
Thanks!
