### ISSUE TITLE
Transparent part shown as black [FIX]

### ISSUE THREAD

**Issue by Dyroxplays** [bs-community/skinview3d#132]
If you have the problem that your skin has a transparency part and it is shown as black, here is the solution:

before:
![Screenshot 2023-04-05 152226](https://user-images.githubusercontent.com/28871798/230128946-9e5827c3-2132-4c90-b7f7-4847e26427cc.png)

after:
![Screenshot 2023-04-05 172411](https://user-images.githubusercontent.com/28871798/230128954-093cc10b-5ec6-4a2a-a54d-d84cc31e2707.png)

Code:
```
skinViewer.playerObject.skin.layer1Material.transparent=true
skinViewer.playerObject.skin.layer1Material.alphaTest=1e-5
skinViewer.playerObject.skin.layer1Material.side=2
skinViewer.playerObject.skin.layer1MaterialBiased.transparent=true
skinViewer.playerObject.skin.layer1MaterialBiased.alphaTest=1e-5
skinViewer.playerObject.skin.layer1MaterialBiased.side=2
```

thanks to @yushijinhun

**Comment by yushijinhun** [comment]
@Hacksore Should we allow the inner layer to contain transparent pixels (though it's not Minecraft's original behavior) by default?

**Comment by Hacksore** [comment]
I'd say make it opt-in so that the default behavior reflects how Minecraft is. 

So my suggestion would be adding a new option like `firstLayerTransperency: true`
