### ISSUE TITLE
Ability To Use Skin Texture Value

### ISSUE THREAD

**Issue by ItsMCB** [bs-community/skinview3d#133]
I'm looking to set the skin viewer's skin based on a skin texture value. 

For example, `ewogICJ0aW1lc3RhbXAiIDogMTY4MjE5MDUyNDM5NywKICAicHJvZmlsZUlkIiA6ICIwNDRhZjIwNDE1OWU0ZDlkYWE0N2ViYTkyNWUyOGNjMCIsCiAgInByb2ZpbGVOYW1lIiA6ICJyZXh0ZXgzMDAwIiwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzIzZmRmMmQ5M2Q3ZjE2NTY3NzY1MDQyNmFjYTE2ODIxZjc3MzIzM2Y0MGZmNDk4ODQ4YmM3YTM0MzYyNDY2NzgiCiAgICB9CiAgfQp9` from [https://sessionserver.mojang.com/session/minecraft/profile/044af204159e4d9daa47eba925e28cc0](https://sessionserver.mojang.com/session/minecraft/profile/044af204159e4d9daa47eba925e28cc0) might look like this:

```javascript
let skinViewer = new SkinViewer({
        canvas: document.getElementById("skin_container"),
        width: 200,
        height: 300,
        animation: new WalkingAnimation(),
        skin: "ewogICJ0aW1lc3RhbXAiIDogMTY4MjE5MDUyNDM5NywKICAicHJvZmlsZUlkIiA6ICIwNDRhZjIwNDE1OWU0ZDlkYWE0N2ViYTkyNWUyOGNjMCIsCiAgInByb2ZpbGVOYW1lIiA6ICJyZXh0ZXgzMDAwIiwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzIzZmRmMmQ5M2Q3ZjE2NTY3NzY1MDQyNmFjYTE2ODIxZjc3MzIzM2Y0MGZmNDk4ODQ4YmM3YTM0MzYyNDY2NzgiCiAgICB9CiAgfQp9"
    });
```

Inputting the value as a string currently won't work because the code expects a string input to mean a texture URL.

**Comment by bribes** [comment]
Why can't you just base64 decode the value and use the skin texture URL itself, you may run into some CORS errors but there are many sites that let you bypass that.

**Comment by ItsMCB** [comment]
That works great. Thank you!
