### ISSUE TITLE
Found 119 errors in 5 files.

### ISSUE THREAD

**Issue by Tobias-Auer** [bs-community/skinview3d#134]
I cannot run the `npm run build` command. I get the following error message:
`Found 119 errors in 5 files.

Errors  Files
    29  src/animation.ts:88
    66  src/model.ts:1
     3  src/nametag.ts:1
    20  src/viewer.ts:1
     1  tsconfig.json:2`

I downloaded the program via GitHub desktop and run the command in the downloaded directory with PowerShell on Win 11.

Have I done sth. wrong?

**Comment by so1ve** [comment]
npm install?
