### ISSUE TITLE
Is there any events or callbacks to listen the skin render?

### ISSUE THREAD

**Issue by mcdoeswhat** [bs-community/skinview3d#147]
Is there any events or callbacks to listen the skin render?

**Comment by Hacksore** [comment]
@mcdoeswhat Could you please provide your use case for this?

Maybe it's related to this issue? https://github.com/bs-community/skinview3d/issues/136

**Comment by mcdoeswhat** [comment]
> @mcdoeswhat Could you please provide your use case for this?
> 
> Maybe it's related to this issue? #136

I want to display a loading element before skin is rendered,now the canvas is just blank before the skin is displayed

**Comment by Hacksore** [comment]
You can use an `Image` and some javascript to wait before you show the canvas.

Here is a demo
https://codesandbox.io/s/skinview3d-image-loading-r5v22n

**Comment by mcdoeswhat** [comment]
> You can use an [`Image`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/Image) and some javascript to wait for the image to load before you show the canvas.
> 
> Here is a demo https://codesandbox.io/s/skinview3d-image-loading-r5v22n

problem solved,thank you very much!
