### ISSUE TITLE
non-alpha skins hat layer

### ISSUE THREAD

**Issue by Hacksore** [bs-community/skinview3d#15]
There needs to be a check for the hat layer before it's applied. Otherwise, it will draw the hat layer when we know that the skin did not intend for that.

![Issue Example](https://i.imgur.com/y6186vG.png)

**Comment by yushijinhun** [comment]
Did you mean the checks here? https://github.com/Hacksore/skinpreview3d.js/blob/80832a17ac31e61939b546520fdf2e068f896f2c/js/skinpreview3d.js#L57

**Comment by Hacksore** [comment]
@yushijinhun I believe so.
