### ISSUE TITLE
gif

### ISSUE THREAD

**Issue by Propants05** [bs-community/skinview3d#152]
its possibile use a gif to load a cape?

linke this
skinViewer.loadCape("https://ww.exemple.com/gif.gif");

**Comment by Hacksore** [comment]
No but @james090500 was working on https://github.com/bs-community/skinview3d/pull/128 not sure of it’s status.

**Comment by james090500** [comment]
I use a fork of this on MinecraftCapes.net but it doesn't load GIFs, instead uses texture maps. 

I think it's on my GitHub or the org
