### ISSUE TITLE
some errors in console

### ISSUE THREAD

**Issue by Propants05** [bs-community/skinview3d#153]
i have this problem 
![image](https://github.com/bs-community/skinview3d/assets/85504551/c16dde4e-c128-447e-948b-e0e341400da4)

I don't know why but many functions that I found on the test page don't work for me

**Comment by Hacksore** [comment]
Can you please provide more information that would help us understand where you see this?

**Comment by bribes** [comment]
Those are just example functions created on the page that use the library. You need to create the functions yourself using skinview3d
