### ISSUE TITLE
If no skin was loaded or skin has transparency the preview is black

### ISSUE THREAD

**Issue by Waradu** [bs-community/skinview3d#154]
![image](https://github.com/bs-community/skinview3d/assets/89935135/98cc6d91-6c30-439a-ade4-46dad2533920)
In places where the image is transparent or if no skin is provided, the skin is black and I think it should be really transparent at these places like the second layer or else it could be confusing.

**Comment by Hacksore** [comment]
The game renders it like this so it's really how it should be. 

We could allow opt-out behaviour with a flag but for now I'm going to close this.

Feel free to work on a PR and I can have a look!
