### ISSUE TITLE
Add way to reset camera position/rotation when autoRotate is set to false

### ISSUE THREAD

**Issue by InstantlyMoist** [bs-community/skinview3d#155]
Hi,

I'd love see a feature where the skin could be auto-reset to it's 'origin position' when autoRotate is set to false.
I'm using the vue-skinview3d for this. They told me to open an issue here.

Is there anything you need from me to make this feature a reality?

Kind regards!

**Comment by Hacksore** [comment]
Def something you could handle in userland.

https://codesandbox.io/p/sandbox/skinview3d-reset-camera-t944st?file=%2Fsrc%2Findex.js%3A20%2C1

cc @so1ve

**Comment by so1ve** [comment]
OMG I completely missed `playerWrapper` before... I even didn't use THREE.JS before 😅 Thanks for the reminder!

**Comment by so1ve** [comment]
Seemed that I couldn't change the player position when `viewer.autoRotate` is set to `false`?

**Comment by Hacksore** [comment]
can you share a branch @so1ve?

**Comment by so1ve** [comment]
Sure!

In your demo: https://codesandbox.io/p/sandbox/skinview3d-reset-camera-t944st?file=%2Fsrc%2Findex.js%3A20%2C1, just delete `viewer.autoRotate = ...`

In `vue-skinview3d`: https://github.com/so1ve/vue-skinview3d/tree/feat/playground/reset-rotation

**Comment by Hacksore** [comment]
I tried the vue code but didnt seem to work but there is `viewer.resetCameraPose()` which I've updated in my demo.

**Comment by InstantlyMoist** [comment]
You guys are amazing, thank you!
