### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by JoCat** [bs-community/skinview3d#157]
It would be nice to have detailed documentation on the various methods of the library. For example, you could use the `typedoc` generator.

**Comment by JoCat** [comment]
I can help with integration, the only thing is that English is not my native language, so the documentation may be crooked (I use deepl translator).

**Comment by Hacksore** [comment]
I believe something that needs to come before this is a monorepo setup that has been discussed in #107.

Once that is setup it would be very easy to drop in typedoc and something like astro.

**Comment by JoCat** [comment]
Well, typedoc can be added with one command, another thing is that we will need to add comments to the code. And so, yes, I think we should wait for the reorganization of the project, we don't need to complicate things now.

**Comment by Hacksore** [comment]
@mochaaP can you please approve the vercel app to be added to this repo so I can setup the docs to auto deploy?

**Comment by mochaaP** [comment]
approved. :)

**Comment by Hacksore** [comment]
Docs are live at https://skinview3d-docs.vercel.app but I think #158 might have broken the github pages deploy for some reason.

**Comment by mochaaP** [comment]
> Docs are live at https://skinview3d-docs.vercel.app but I think #158 might have broken the github pages deploy for some reason.

could be github api changes. updating CI deps may work.

**Comment by gxres042** [comment]
> Docs are live at https://skinview3d-docs.vercel.app but I think #158 might have broken the github pages deploy for some reason.

https://github.com/bs-community/skinview3d/blob/5700926955ae0698510a71a4e42b452771c57c8b/.github/workflows/pages.yaml#L52

I suggest to use actions/upload-pages-artifact@v3

https://github.com/gxres042/skinview3d/blob/125f1b703e01e39461a7bb9ca27e2193f52df78c/.github/workflows/pages.yaml#L52
https://github.com/gxres042/skinview3d/actions/runs/7517237253/job/20463180283

**Comment by JoCat** [comment]
I must have generated the documentation from the wrong file because it even has clear comments, cool 👍
