### ISSUE TITLE
Help with Animation progress

### ISSUE THREAD

**Issue by bribes** [bs-community/skinview3d#160]
I want to make the Walking Animation start paused at a certain progress. How can I do this?

**Comment by Hacksore** [comment]
From what I can tell in the implementation you'd have to add functionality to this or move all the parts yourself.

https://github.com/bs-community/skinview3d/blob/694085b3d2f5a4250cdc96084bb9f09daafa5656/src/animation.ts#L94-L130

**Comment by bribes** [comment]
Alright
