### ISSUE TITLE
Show only heads with skinview3d

### ISSUE THREAD

**Issue by DarthGigi** [bs-community/skinview3d#161]
Is it possible to tell skinview3d to show only the head and not the full body? I currently use [headview3d](https://github.com/SMCodesP/headview3d) but would rather use skinview3d as headview3d isn't being updated. If not, could support for this be added?

**Comment by Hacksore** [comment]
This is possible with some disabling of certain parts, it's not perfect but it works.

https://codesandbox.io/p/sandbox/skinview3d-head-only-2nmhvt

Maybe @SMCodesP can raise a PR to add this functionally here 🙏.

**Comment by SMCodesP** [comment]
Hi @Hacksore,

Thank you for mentioning me! I appreciate it. I'll do my best to create a pull request with the functionalities that headview3d offers. I initially created it for a personal project that I abandoned some time ago, but I'll try to provide support for the latest commits and maybe submit a pull request that directly implements an option for headview only.

**Comment by DarthGigi** [comment]
Hey @SMCodesP,

I hope you're doing great. I was wondering if there has been any progress on this issue?

**Comment by SMCodesP** [comment]
Hello @DarthGigi, I was analyzing the old code of my fork, as it is very outdated as you said, there were many merge errors, so initially I tried to reimplement the code already in the main code and add the option to just render the head, but this would possibly take some time to analyze and try for personal time reasons, so I will just update the code of the old library and, over time, I will send a PR for the main code to implement it as an option.

**Comment by SMCodesP** [comment]
@DarthGigi 

Hello, how are you?
I've updated the code to the latest version of Skinview3d. This time, I didn't implement it directly into the original code. Instead, I removed functionalities that are not related to rendering the character's head. Therefore, my fork currently doesn't aim to make a pull request for obvious reasons that it would harm the source code. For now, I don't have much time to implement an option in the original code to simply render the head. However, perhaps soon I'll make some contribution to the source code through a pull request. Below are the links to the template on CodeSandbox, the fork, and the npm link:

Template on CodeSandbox: https://codesandbox.io/p/sandbox/headview3d-template-9ck47g
Fork link: https://github.com/SMCodesP/headview3d
NPM link: https://www.npmjs.com/package/headview3d

**Comment by DarthGigi** [comment]
> @DarthGigi
> 
> Hello, how are you? I've updated the code to the latest version of Skinview3d. This time, I didn't implement it directly into the original code. Instead, I removed functionalities that are not related to rendering the character's head. Therefore, my fork currently doesn't aim to make a pull request for obvious reasons that it would harm the source code. For now, I don't have much time to implement an option in the original code to simply render the head. However, perhaps soon I'll make some contribution to the source code through a pull request. Below are the links to the template on CodeSandbox, the fork, and the npm link:
> 
> Template on CodeSandbox: [codesandbox.io/p/sandbox/headview3d-template-9ck47g](https://codesandbox.io/p/sandbox/headview3d-template-9ck47g) Fork link: [SMCodesP/headview3d](https://github.com/SMCodesP/headview3d) NPM link: [npmjs.com/package/headview3d](https://www.npmjs.com/package/headview3d)

Thank you so much @SMCodesP! I really appreciate it!

**Comment by Hacksore** [comment]
Thanks @SMCodesP! Going to close this for now.
