### ISSUE TITLE
Can I get only the 3D model?

### ISSUE THREAD

**Issue by Nazar0n** [bs-community/skinview3d#164]
I would really benefit from your library, but unfortunately, I can't use it in React Native. I could try to implement something myself, but I have a problem, how do I convert a PNG skin to a 3d model? Maybe this library already has a ready-made function for this?

**Comment by Hacksore** [comment]
Pretty sure we can’t easily support react-native but I did see this as a starting point.

https://snack.expo.dev/@danstepanov/3d-playground
