### ISSUE TITLE
Is there a way to detect if there is anything on a skins second layer?

### ISSUE THREAD

**Issue by bribes** [bs-community/skinview3d#165]
Title ^

**Comment by Hacksore** [comment]
We probably could expose a bunch of these helper methods from `skinview-utils` but here is how you'd do it.

https://codesandbox.io/p/sandbox/skinview3d-skin-second-layer-gjqmfc

**Comment by Hacksore** [comment]
that demo is also likely missing more layer 2 parts but should help you get to a working solution.
