### ISSUE TITLE
How to import and use skinview3d in nodejs, with electronjs... ?

### ISSUE THREAD

**Issue by Nokaji** [bs-community/skinview3d#166]

**Comment by Hacksore** [comment]
Hi @Nokaji,

You would use either a package manager like `npm` to install the dep or a cdn like https://unpkg.com 

Then following the [README.md](https://github.com/bs-community/skinview3d/blob/master/README.md) you can do something like this.

```html
<canvas id="skin_container"></canvas>
<script>
	let skinViewer = new skinview3d.SkinViewer({
		canvas: document.getElementById("skin_container"),
		width: 300,
		height: 400,
		skin: "img/skin.png"
	});
</script>
```

If you need more help you might want to try a discord like https://discord.com/invite/electronjs or https://discord.com/invite/web.

**Comment by Nokaji** [comment]
I have this : ```
Unhandled Exception UnhandledRejection TypeError: Failed to resolve module specifier 'skinview3d'
    at renderSkin (file:///E:/Documents/Leandre/FluxLauncher/app/assets/js/scripts/launcher.js:74:22)
    at file:///E:/Documents/Leandre/FluxLauncher/app/assets/js/scripts/launcher.js:83:1
``` with this `async function renderSkin(){
  const skinview3d = await import("skinview3d");
  let skinViewer = new skinview3d.SkinViewer({
    canvas: document.getElementById("skin_container"),
    width: 300,
    height: 400,
    skin: await SkinManager.getActualSkin(),
  });
}

renderSkin();`

**Comment by Hacksore** [comment]
@Nokaji No issues using dynamic import for me, at least in an a codesandbox.

https://codesandbox.io/p/sandbox/skinview3d-dynamic-import-d6zg8t

Electron support for for ESM/dynamic import is on 28.x and later so make sure to update.

https://www.electronjs.org/docs/latest/tutorial/esm
