### ISSUE TITLE
Elytra Support

### ISSUE THREAD

**Issue by skmedix** [bs-community/skinview3d#20]
As in https://github.com/to2mbn/skinview3d/issues/20#issuecomment-385192936

**Comment by Hacksore** [comment]
@skmedix So support for the gilder? 

From the wiki:

> Elytra (About this sound /ˈɛl ɪ trə/ (IPA key) ᴇʟ-i-trə (respell key) but often /ɛl ˈaɪ trə/) are an item that allows the player to glide, and fly under certain conditions. They are gray in color unless the player is wearing a cape, in which case the elytra will adopt the cape's design.

**Comment by skmedix** [comment]
Yes. Since 1.9 cape image contains a "skin" for the elytra.
Example:
![Cape with elytra](https://user-images.githubusercontent.com/3246162/39399266-1778431e-4b1b-11e8-85ee-11e149d1f030.png)

In a 3D model it looks like:
![image](https://user-images.githubusercontent.com/3246162/39399271-314b3882-4b1b-11e8-86b1-255fbb103a04.png)

**Comment by yushijinhun** [comment]
I'm not good at 3D modelling. So, this feature is a bit difficult for me to implement.

**Comment by yushijinhun** [comment]
I'm trying to implement this feature (see [`elytra` branch](https://github.com/bs-community/skinview3d/tree/elytra)).

![default](https://user-images.githubusercontent.com/8373027/45918952-1845e700-bec1-11e8-910b-85d65a8330fa.png)

**Comment by jinzhijie** [comment]
这看起来已经很久没有更新了，希望能快点实现此功能
This looks like it hasn’t been updated for a long time, I hope to implement this feature soon.

**Comment by yushijinhun** [comment]
Sorry for that. I almost have no idea how to implement it, since I'm not familiar with modeling and animating. Also, in months I will graduate from senior high, so I don't have enough time currently.

I have tagged this issue as "help wanted", and I would appreciate it if anyone could help.

**Comment by james090500** [comment]
I have a somewhat working fork which supports deadmau5 ears, elytras and animated capes.

https://github.com/james090500/skinview3d

I have had to hack some stuff together to override the default SkinUtil components.

**Comment by yushijinhun** [comment]
@james090500 Great job! I'm hoping to have your code merged.

**Comment by james090500** [comment]
Feel free to use as much as you like, you'll need to replace some bits into SkinUtils and possibly improve my awful type script.
