### ISSUE TITLE
Discussion on the ownership transfer of the repository

### ISSUE THREAD

**Issue by yushijinhun** [bs-community/skinview3d#23]
The current owner of the repository is @to2mbn, an organization created by @Darkyoooooo and me years ago. The organization was aimed to gather Minecraft lovers in China and build things together.

But in fact it didn't go this way. I have discussed with @Darkyoooooo recently, and we are going to dissolve this organization. So we have to find a successor owner.

Currently, I feel like transfering the ownership to @bs-community. The organization is run by multiple persons. The [Blessing Skin Server](https://github.com/printempw/blessing-skin-server/blob/master/README_EN.md) project, maintained by this organization, is also a major user of skinview3d. This is the reason why I choose it.

I'm leaving this issue open to collect comments about the ownership transfer. If there is no objection, I will perform the ownership transfer in July.

BTW, I'm coming back to the development this July, planning to add some wonderful features.

**Comment by yushijinhun** [comment]
@Hacksore , what do you think of this?

**Comment by Hacksore** [comment]
I have no issues with this.
