### ISSUE TITLE
Move to Typescript

### ISSUE THREAD

**Issue by Hacksore** [bs-community/skinview3d#29]
I would love to see this project completely written in typescript. If I have time I can start working on a typescript branch.

It would make things a lot nicer not having to depend on type definition files. Furthermore, since I'm always writing typescript now it just feels more natural.

What is everyone else's thoughts on this?

**Comment by yushijinhun** [comment]
That's great.

Since typescript is compatible with javascript, I think you don't need to start from scratch. You can first delete these type definition files, then change the existent files from javascript to typescript step by step. (This is just my suggestion.)

@g-plane is good at typescript. If you have problems, let him and me know. I wish it will be a success.

**Comment by Hacksore** [comment]
@yushijinhun 

Let me see if we can get at least a working

**Comment by g-plane** [comment]
@Hacksore If you are using Chrome or Firefox, I recommend you to install a browser extension called "refine-github" which brings a feature that move the "close" button to the left to prevent misoperation.

**Comment by yushijinhun** [comment]
@Hacksore You can create a `typescript` branch. When the work is done, it will be merged into `master`.

**Comment by Hacksore** [comment]
@g-plane I made a rough draft of the Typescript branch. Not sure how we implement all of the files being transpiled or if the work at this point.

Would you mind taking a look?

**Comment by g-plane** [comment]
@Hacksore Why you commented out the tests?

**Comment by g-plane** [comment]
In the `tsconfig.json`:
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015"
  }
}
```

Then use `rollup-plugin-typescript` or `rollup-plugin-typescript2` to bundle it.

**Comment by Hacksore** [comment]
@g-plane I got it working but need to see what happend to the arms xD

![image](https://user-images.githubusercontent.com/996134/43031299-9d7a05da-8c64-11e8-83f2-318ec0782385.png)

**Comment by yushijinhun** [comment]
@Hacksore Just add this line back: https://github.com/bs-community/skinview3d/commit/a48f935f06f70717355b0b0f62d2cb684afe1ddd#diff-a6322b30cb17d35f81779ff7980ea4c3R352

**Comment by Hacksore** [comment]
@yushijinhun It is but I might have made mistake elsewhere. 

https://github.com/bs-community/skinview3d/commit/b2932c96bb68727e03f7b0075d7286891895308b

**Comment by Hacksore** [comment]
@g-plane Can you help with fixing the unit tests on the typescript branch?

**Comment by g-plane** [comment]
Sure. Any problems?

**Comment by g-plane** [comment]
@Hacksore And, some compiler options in tsconfig.json are redundant.

**Comment by Hacksore** [comment]
@g-plane feel free to make any suggestions on the tsconfig options.

**Comment by g-plane** [comment]
I may do changes and push to this branch directly tomorrow.

**Comment by g-plane** [comment]
Sorry for delay! I have fixed the tests.

**Comment by g-plane** [comment]
@Hacksore Any updates?

**Comment by Hacksore** [comment]
@g-plane Have not had time to work on this, let me see if I can work on it today.

**Comment by Hacksore** [comment]
I've pushed all my changes for now. Really we need to go through the source and do some refactoring for a lot of the class fields. In my first pass through almost all of them are public. As well as move the function from the util file into a proper class definition.

I'm on slack so that's probably the best way to collab on this.

**Comment by yushijinhun** [comment]
Done in #31.
