### ISSUE TITLE
Simplified programmatic access to body parts

### ISSUE THREAD

**Issue by Hacksore** [bs-community/skinview3d#32]
This was a question asked by @johnrippus over on gitter.

Right now we don't have a way to access body part references easily. I'm working on a branch for this so that it would be possible to get the reference to a part via a lookup method.

However, this does require some more boilerplate code to manage all the parts.

![image](https://user-images.githubusercontent.com/996134/46711137-a1268780-cc10-11e8-836b-21036c9a5d7c.png)

@yushijinhun @g-plane What are your thoughts on this?

**Comment by g-plane** [comment]
What should it return?

**Comment by yushijinhun** [comment]
https://github.com/bs-community/skinview3d/blob/master/src/model.ts#L42-L47

Get the head part using `skinViewer.playerObject.skin.head`

**Comment by yushijinhun** [comment]
What about adding a property to the body parts, eg. `skinViewer.playerObject.skin.rightArm.helmLayer`?

We can create a class named `BodyPart`, and let it inherit from `THREE.Group`, putting `baseLayer` and `helmLayer` properties in it.

**Comment by Hacksore** [comment]
Sounds like a good idea.

**Comment by yushijinhun** [comment]
Implemented in #33
