### ISSUE TITLE
Automation of code updating on skinview3d.com

### ISSUE THREAD

**Issue by Hacksore** [bs-community/skinview3d#35]
I'd like to create a script to update the s3 bucket code for this demo on https://skinview3d.com/

Not sure where I should run this script but it should run at least once a week to check for newer versions of the skiview3d code. If it finds a new version it will download the source and compile then upload to s3.

**Comment by yushijinhun** [comment]
Since we don't release very often, running the script manually is enough, I think.

**Comment by Hacksore** [comment]
I'm looking at moving web hosting to firebase so that maybe it's easier to just run the cli command `npm run deploy`. It could run a shell script similar to that of the gh-pages one.

**Comment by Hacksore** [comment]
At some point https://skinview3d.com should start working.

Here is the app URL https://skinview-ad73a.firebaseapp.com/

Marking this issue closed as now I can invoke `npm run deploy` and it will do all the steps to get the latest code.
