### ISSUE TITLE
Drop the alpha tag suffix in version

### ISSUE THREAD

**Issue by Hacksore** [bs-community/skinview3d#38]
@yushijinhun @g-plane 

I think it's safe to drop the alpha suffix and publish `1.2.0`, thoughts?

**Comment by g-plane** [comment]
I don't mind it.

**Comment by yushijinhun** [comment]
@Hacksore Take a look at [animation-refactor](https://github.com/bs-community/skinview3d/tree/animation-refactor) branch. I'm wanting these features in next release, but haven't thoroughly tested them yet.
