### ISSUE TITLE
Package size is too large

### ISSUE THREAD

**Issue by ShirasawaSama** [bs-community/skinview3d#40]
At present, this module directly imports `Three.js`:

```ts
import * as THREE from 'three'
```

So the bundle files contains about **500kb** of `Three.js` codes. It is too huge.

So you can reduce the bundling size by this ways:

- Tree Shaking.
- Import `Three.js` by this way:

```ts
import Vector2 from 'three/src/math/Vector2'
```

-----

当前模块由于直接引入了 `Three.js` , 导致打包大小贼大 (大约 **500kb** ):

```ts
import * as THREE from 'three'
```

这些是一些解决方法:

- 使用 `Tree Shaking` (首先得改文件里导入 `Three.js` 的写法, 最好用 [bili](https://npmjs.com/bili) 或者 [rollup](https://npmjs.com/rollup) 弄个包含了 Tree Shaking 后的 `Three.js` 源码的模块)
- 单独导入子模块:

```ts
import Vector2 from 'three/src/math/Vector2'
```

**Comment by g-plane** [comment]
我们已经有在使用 Rollup。后面一种写法确实可以做到 tree shaking，但还需要确定这样能不能得到Three.js 的 TypeScript 类型定义。

**Comment by yushijinhun** [comment]
You should nkt

**Comment by ShirasawaSama** [comment]
@g-plane 尝试了一下, 是可以的:

tsconfig.json:

```json
{
  "moduleResolution": "node"
}
```

a.ts:

```ts
import { Vector2 } from 'three/src/math/Vector2'

new Vector2(...)
```

**Comment by g-plane** [comment]
感谢帮忙测试。

**Comment by ShirasawaSama** [comment]
我可以提交pr, 但是我仍旧希望提供一个预先打包好threejs的版本(

**Comment by g-plane** [comment]
「预先打包好 threejs 的版本」？这是指？

**Comment by ShirasawaSama** [comment]
好像原本就有了(umd)

就是我的程序中不方便使用 tree shaking, 然后就是预先把threejs也打包进这个模块的发布版本中, 就不需要另外打包threejs了, 其实就是 TreeShaking 后的 `Skinview3d+Threejs`

**Comment by g-plane** [comment]
就是包含一个不完整的 Three.js，是吗？

**Comment by ShirasawaSama** [comment]
是的

**Comment by g-plane** [comment]
我感觉 Rollup 已经进行过 tree shaking，因为 Three.js 的完整压缩 build 有 500 多 KB，而 skinview3d 的压缩 build 只有 24KB。

**Comment by ShirasawaSama** [comment]
600kb->398kb

**Comment by g-plane** [comment]
这个是？

**Comment by ShirasawaSama** [comment]
修改了引入方式之后打包的

**Comment by g-plane** [comment]
但是现在在没有做任何改动的情况下，也才 57.6KB，而压缩后更只有 24KB。

**Comment by ShirasawaSama** [comment]
打包了threejs之后的uglify之后的大小

**Comment by g-plane** [comment]
已经包含了 Three.js 了，skinview3d 本身是很小的。

**Comment by g-plane** [comment]
稍等……

**Comment by yushijinhun** [comment]
Reopened due to https://github.com/bs-community/skinview3d/pull/41#issuecomment-570034308

**Comment by yushijinhun** [comment]
Other users of three.js are also facing this problem. Take a look at https://github.com/mozilla/Spoke/issues/747.

**Comment by yushijinhun** [comment]
@ShirasawaSama I'm working on a rollup plugin [three-minifier](https://github.com/yushijinhun/three-minifier). Currently, the bundle (skinview3d & three.js) it produces is about 377KB.

**Comment by yushijinhun** [comment]
I've just released [three-minifier v0.1.1](https://twitter.com/yushijinhun/status/1221415525139378176). I think it is a good solution to this problem, so I'm going to close this issue.
