### ISSUE TITLE
Feat: pause rendering?

### ISSUE THREAD

**Issue by ShirasawaSama** [bs-community/skinview3d#42]
I want to pause rendering, but not `dispose`.

e.g.

```ts
const viewer = new Viewer(...)

// whem modal window close:
modal.on('off', () => viewer.pauseRender()) // or viewer.pauseDraw()

// open:
modal.on('open', () => viewer.continueRender()) // or viewer.draw()
```

But now, when I call `viewer.dispose()`, the instance is destroyed.

When I call `viewer.disposed = false`, it can't be restored from pausing.

I want to interrupt the execution of `window.requestAnimationFrame()` , but also can be restored.

Can you expose the `draw` method?

These two methods can also be named `pauseDraw` and `draw`.

**Comment by g-plane** [comment]
Can you tell us detail of `pauseRender`?

**Comment by ShirasawaSama** [comment]
把 `viewer.ts` 里构造函数的 `draw` 函数提取出来, 可以让开发者中断渲染, 因为如果容器被遮挡了还是一直在调用渲染函数
