### ISSUE TITLE
[feature] render in 2d

### ISSUE THREAD

**Issue by cheel1337** [bs-community/skinview3d#44]
Hey. I want to show only the head of the skin. I made this code
```ts
const parts = viewer.playerObject.skin;
const invisible = ['body', 'leftArm', 'rightArm', 'leftLeg', 'rightLeg'];
            
for(const part of invisible) {
      parts[part].visible = false;
}
```

But it just hides other parts of the skin and the head does not get the entire area of the canvas.
I get this:
![Снимок экрана 2020-01-05 в 22 29 51](https://user-images.githubusercontent.com/42740773/71785092-9e316700-300c-11ea-9809-68f297bb6aaa.png)
![Снимок экрана 2020-01-05 в 22 30 36](https://user-images.githubusercontent.com/42740773/71785096-aa1d2900-300c-11ea-9d9a-fed37f0d314e.png)

But i need something like this:
![Снимок экрана 2020-01-05 в 22 45 03](https://user-images.githubusercontent.com/42740773/71785141-27e13480-300d-11ea-997f-10dbdfdaabab.png)

**Comment by Hacksore** [comment]
@cheel1337 I think this is out of scope for this library IMO. My old lib is unmainted at this point so I would not recommend using it [skinpreview.js](https://github.com/Hacksore/skinpreview.js).

@g-plane @yushijinhun Do you want to add some feedback here as well? I'm not saying we can't support this feature as it could have some value. However, I think all the overhead that three.js adds might make it a better feature in a separate lib (aka skinpreview.js v2.0).

**Comment by yushijinhun** [comment]
I can create a separate library for this, and I would like to name it 'skinview2d'. How do you think guys?

**Comment by cheel1337** [comment]
@yushijinhun It would be cool!

**Comment by yushijinhun** [comment]
@Hacksore I think some code can be shared between the two projects(eg. [src/utils.ts](https://github.com/bs-community/skinview3d/blob/master/src/utils.ts)). How do you think we should deal with them? I have come up with some solutions:
1. Release them in another npm package(eg. `skin-utils`), and use it as a dependency. But this would add to the complexity.
2. Put them in another repository, and use git submodule.
3. Just copy&paste and maintain them separately.

**Comment by g-plane** [comment]
Use lerna.

**Comment by Hacksore** [comment]
I say for now we just keep the code in the new `skinview2d` project to lower complexity.

If we do see a need for sharing some code we can surely look at creating `skin-utils` as they could be useful in a generic sense for any project working with skins.

**Comment by yushijinhun** [comment]
I've created the repository [bs-community/skinview2d](https://github.com/bs-community/skinview2d).

**Comment by Hacksore** [comment]
I'm still trying to find time to commit to [bs-community/skinview2d](https://github.com/bs-community/skinview2d) but no timelines as of now.

Help from anyone is welcomed.

**Comment by Hacksore** [comment]
We can take up any further discussion regarding 2d in [bs-community/skinview2d](https://github.com/bs-community/skinview2d).
