### ISSUE TITLE
Setting capeUrl to null should hide it

### ISSUE THREAD

**Issue by Hacksore** [bs-community/skinview3d#48]
I ran into this issue and it's also noted here. When we set the cape to null it should automatically hide the cape, then when setting it again it will unhide it.

https://github.com/bs-community/skinview3d/blob/b3858b598f2085d344a5015a08eb4a9ee3474d89/js/example.js#L58-L64

**Comment by yushijinhun** [comment]
We are going to redesign SkinViewer class (https://github.com/bs-community/skinview-utils/issues/3), and `skinUrl`/`capeUrl` will no longer exist. Will you face similar problems after that? @Hacksore
