### ISSUE TITLE
I cannot run the project

### ISSUE THREAD

**Issue by adamandworking** [bs-community/skinview3d#50]
Would you please tell me the steps to run this project please?
I have done "npm install" and then I run "npm run build". Some errors happen.

> src/skinview3d.ts → bundles/skinview3d.bundle.js...
> [!] (plugin at position 1) TypeError: code.matchAll(...) is not a function or its return value is not iterable
> 
I need some help ;(

**Comment by g-plane** [comment]
Do you want to contribute to this project or just want to use this library?

**Comment by adamandworking** [comment]
I just want to use this library. As I am working on a stylegan2 project on Minecraft Skin, I want to use this library to save the 3D view of tons of 2D png images. I would add some code in it if needed. E.g. Add snapshot function in it.

**Comment by g-plane** [comment]
You can install this library from npm directly.

**Comment by Hacksore** [comment]
So as of now node >= 12 is required to build this project due to @yushijinhun/three-minifier-rollup

**Comment by Hacksore** [comment]
@adamandworking As @g-plane mentioned you can just install via `npm` is it's already built for you.

However, if you do want to build yourself to add features then please use node version >= 12
