### ISSUE TITLE
Incorrect skin overlay on the model

### ISSUE THREAD

**Issue by MrZillaGold** [bs-community/skinview3d#51]
When applying a normal skin to a slim model, incorrect overlay of pixels on the hands occurs.
```js
viewer.detectModel = false;
viewer.playerObject.skin.slim = true;
```
![image](https://user-images.githubusercontent.com/42776347/77523019-d7bd9400-6ed0-11ea-89f9-b0847e8fcd09.png)

Skin:
![image](https://user-images.githubusercontent.com/42776347/77522779-84e3dc80-6ed0-11ea-981e-3abeaaf4e5d4.png)

**Comment by yushijinhun** [comment]
This is the expected behavior which is the same in the game. You cannot apply a normal skin to a slim model, and vice versa.

**Comment by MrZillaGold** [comment]
Indeed, this is normal behavior, these pixels are applied to the second layer. Sorry for the worry.
