### ISSUE TITLE
The example is giving me the following error.

### ISSUE THREAD

**Issue by JuanFHaretche** [bs-community/skinview3d#57]
![image](https://user-images.githubusercontent.com/63614406/86864303-5070e680-c0a3-11ea-9316-b5f68644c119.png)
![image](https://user-images.githubusercontent.com/63614406/86864582-d3923c80-c0a3-11ea-8a6c-08e1be43fa2c.png)

**Comment by g-plane** [comment]
It seems that you haven't run `npm i`.

**Comment by JuanFHaretche** [comment]
Thanks! I thought I already had installed it because I have node.js and its says that node comes with npm.
