### ISSUE TITLE
Add dist code to repo

### ISSUE THREAD

**Issue by Hacksore** [bs-community/skinview3d#58]
Seems this is a common practice among other big repositories. More so in order to support this project on cdnjs I think we will need to do this.

See the related PR to track this effort on the cdnjs side https://github.com/cdnjs/packages/pull/334

**Comment by g-plane** [comment]
I think adding them will mess up the repository.

**Comment by Hacksore** [comment]
@g-plane If you look at three.js they do it so not sure why it would be an issue for us? 

https://github.com/mrdoob/three.js/tree/dev/build

**Comment by yushijinhun** [comment]
@Hacksore I don't think three.js has done it right.

If you want to publish this repo to cdnjs, what about using [NPM-based auto-update](https://github.com/cdnjs/packages/blob/master/CONTRIBUTING.md#npm-based-auto-update-example)? Build outputs are included in npm package.

**Comment by Hacksore** [comment]
@yushijinhun fair point but looks like we are not popular enough for this 😐.

![image](https://user-images.githubusercontent.com/996134/86997997-0bb58000-c175-11ea-94b6-e2f4e6dbb4e7.png)


https://github.com/cdnjs/packages/runs/852594368

**Comment by yushijinhun** [comment]
@Hacksore [unpkg.com](https://unpkg.com/) is a good alternative. Both cdnjs and unpkg are hosted on Cloudflare, so there shouldn't be much difference in network speed.

**Comment by Hacksore** [comment]
@yushijinhun Oh cool. This looks like less work too.

Latest version:
https://unpkg.com/skinview3d/bundles/skinview3d.bundle.js

Specific version:
https://unpkg.com/skinview3d@2.0.0-alpha.5/bundles/skinview3d.bundle.js
