### ISSUE TITLE
Not working in some browsers

### ISSUE THREAD

**Issue by thallysbr** [bs-community/skinview3d#63]
Browsers that i tested and it's not working:

- Edge

Error:
SCRIPT5009: SCRIPT5009: 'ImageBitmap' is not defined

**Comment by Hacksore** [comment]
@thallysbr can you let us know what version of Edge? I'm guessing the non-chromium based is affected as I tried the latest Edge and didn't see any issue.

**Comment by Hacksore** [comment]
I looked for references and could just be an outdated version of three.js.

https://github.com/mrdoob/three.js/issues/16274

**Comment by yushijinhun** [comment]
[Browser support of ImageBitmap API](https://caniuse.com/#feat=mdn-api_imagebitmap)

https://github.com/bs-community/skinview-utils/blob/9b7f1d5cd5968f4d828f5aba30ee16be8f539034/src/viewer-mixins.ts#L15-L17

In browsers that do not support `ImageBitmap`, evaluating `x instanceof ImageBitmap` will result in an error.
