### ISSUE TITLE
How do i put it in a website

### ISSUE THREAD

**Issue by Gummybearman06** [bs-community/skinview3d#64]
i'm new to html, and i have no idea how to put this in a website. Do i just paste in the whole folder? I dont really know what else i would do...

**Comment by Hacksore** [comment]
@Gummybearman06 Please look at this example it should help you.

https://codesandbox.io/s/skinview3d-example-i6fuk?file=/index.html

**Comment by Gummybearman06** [comment]
> @Gummybearman06 Please look at this example it should help you.
> 
> https://codesandbox.io/s/skinview3d-example-i6fuk?file=/index.html
I don't understand, there are no instructions as to what to do
