### ISSUE TITLE
transparent anti-aliasing black borders

### ISSUE THREAD

**Issue by nstringham** [bs-community/skinview3d#78]
when alpha is set to true with anti-aliasing turned on there are weird black borders
```js
new skinview3d.FXAASkinViewer({
    alpha: true
});
```
![image](https://user-images.githubusercontent.com/44071655/96197176-4753a900-0f1f-11eb-9353-68e81eec3920.png)

**Comment by yushijinhun** [comment]
Using FXAA and transparent backgrounds at the same time is not recommended.(see [readme](https://github.com/bs-community/skinview3d#anti-aliasing))

Does your problem still exist if you set `alpha` to false?

**Comment by nstringham** [comment]
> Does your problem still exist if you set alpha to false?

No only when the background is transparent

> Using FXAA and transparent backgrounds at the same time is not recommended.(see readme)

Oh I guess I missed that part thanks for pointing that out
