### ISSUE TITLE
position of body parts

### ISSUE THREAD

**Issue by IPeredero** [bs-community/skinview3d#81]
how to change the pose of the hands and head?

**Comment by yushijinhun** [comment]
Just take a look at [the implementation of walking animation](https://github.com/bs-community/skinview3d/blob/4c4acf950164bd6ac6787993a680faf6cc922497/src/animation.ts#L136-L160), and you will know how it's done.

For example:
![image](https://user-images.githubusercontent.com/8373027/108262317-bed06800-719f-11eb-9e0f-166b91ba154c.png)
