### ISSUE TITLE
why is canvas focusable

### ISSUE THREAD

**Issue by nstringham** [bs-community/skinview3d#83]
the canvas has `tabindex="0"` but why? it's not keyboard accessible by default

**Comment by yushijinhun** [comment]
See https://github.com/mrdoob/three.js/commit/fe7aa22c35fe84ebc6bb7b508649cddf4f40761f.

After upgrading three.js to r125 (https://github.com/bs-community/skinview3d/commit/4dcca770cab1735aa81f827f114e7900e50649be), this bug should be fixed.
