### ISSUE TITLE
[feature request] modelType in constructor

### ISSUE THREAD

**Issue by nstringham** [bs-community/skinview3d#84]
This is a feature request for a way to set a skin's modelType directly from the SkinViewer constructor inside the SkinViewerOptions object.

### who is requesting this feature and why:
me (Nate Stringham) I am a contributor to [SkyCrypt](https://sky.shiiyu.moe/) and realized that solving SkyCryptWebsite/SkyCrypt#455 would be much easier if skinview3d allowed a model to be passed into the constructor

### the problem that this feature would solve:
currently, it seems difficult to initialize a viewer with a model. the following code doesn't work because the auto-detect feature overrides modelType as soon as the skin is loaded.
```js
skinViewer = new skinview3d.SkinViewer({
    skin: skin_data.skinurl,
    cape: skin_data.capeurl
});
skinViewer.playerObject.skin.modelType = skin_data.model;
```

the following code does work but requires an extra step and it would be nice if it could be done directly in the constructor
```js
skinViewer = new skinview3d.SkinViewer({
    cape: skin_data.capeurl
});
skinViewer.loadSkin(skin_data.skinurl, skin_data.model);
```

### why not just use the auto-detected model:
because some users use an incorrect model with their skin intentionally and we would like to respect that desition

### what would this feature look like if added:
it would look something like this:
```js
skinViewer = new skinview3d.SkinViewer({
    skin: skin_data.skinurl,
    cape: skin_data.capeurl,
    modelType: skin_data.model
});
```

**Comment by yushijinhun** [comment]
It's in v2.0.1

**Comment by nstringham** [comment]
Thanks
