### ISSUE TITLE
Add a way to execute a function on “Bad Cape Size”

### ISSUE THREAD

**Issue by withdrew** [bs-community/skinview3d#87]
Add something like skinViewer.capeTexture.onBadCapeSize or something similar. Since I want to be able to resize the cape texture if the cape size isn’t compatible. I want to be able to do something like skinViewer.capeTexture.onBadCapeSize = function() { something };

**Comment by Hacksore** [comment]
@withdrew This might help you

https://codesandbox.io/s/skinview3d-bad-cape-v00l7?file=/src/index.js

**Comment by withdrew** [comment]
> @withdrew This might help you
> 
> https://codesandbox.io/s/skinview3d-bad-cape-v00l7?file=/src/index.js
this doesnt work for me. I use a api thats on a different domain so idk if that why,

**Comment by yushijinhun** [comment]
> 
> 
> @withdrew This might help you
> 
> https://codesandbox.io/s/skinview3d-bad-cape-v00l7?file=/src/index.js

`loadCape` is an async function, so you have to use `await skinViewer.loadCape(...)`.

```js
(async () => {
  try {
    await skinViewer.loadCape("./test.png");
  } catch (err) {
    console.log("Bad cape image");
    console.log(err);
  }
})();
```

**Comment by withdrew** [comment]
ty
