### ISSUE TITLE
Is it possible to flip the character and controls

### ISSUE THREAD

**Issue by withdrew** [bs-community/skinview3d#88]
Is it possible to flip the character and controls? I'm trying to flip the character and controls for dinnerbone.

**Comment by withdrew** [comment]
hey, any updates?

**Comment by yushijinhun** [comment]
Just rotate the PlayerObject around the Z axis.
```js
skinViewer.playerObject.rotation.z = Math.PI;
```

**Comment by withdrew** [comment]
Thank you! <3
