### ISSUE TITLE
npm watch command for local development

### ISSUE THREAD

**Issue by Hacksore** [bs-community/skinview3d#9]
Could we implement an npm script like this for real-time transpilation? This would also require an html file with the basic construct of the skin viewer.

Something like :
`npm run watch`

```
rollup -c tools/rollup.browser.min.js -w
```

We can discuss this more detail and figure out what works best. Currently, I have a local branch and it's working well to play around with the animation system.

**Comment by yushijinhun** [comment]
> This would also require an html file with the basic construct of the skin viewer.

This is the very point I'm thinking about. We can put these test files (including htmls, skins, capes) in `/exmaples` or `/test` directory. But I have some questions:
 * Should them be published to the npm repository?
 * Will they be duplicated with the examples in `gh-pages` branch?
 * Will they bring any legal problems if we use copyrighted textures?

For the 3rd question, we can request the texture author's permission. But this will take some time.

For the 2nd question, I'm planning about use scripts to update `gh-pages` periodically (e.g. every time a version is released). But I don't think it's the best solution, so what's your idea?

**Comment by g-plane** [comment]
How about using parcel?

**Comment by Hacksore** [comment]
> Should them be published to the npm repository?

I like the idea of a /test or /examples folder in the master repo. We can exclude them from the npm module with a `.npmignore` file, right? 

> Will they be duplicated with the examples in gh-pages branch?

Currently, it sounds like they might just be duplicated into the master branch. We could also make some kind of build script like you mentioned for the gh-pages branch so we don't have to periodically update the codebase for that branch.

> Will they bring any legal problems if we use copyrighted textures?

Probably not. We can just use some basic skins that I create so that there are no copyright issues.

**Comment by yushijinhun** [comment]
> Probably not. We can just use some basic skins that I create so that there are no copyright issues.

I agree with you. Some textures are really too hard to find, e.g. HD capes, HD Alex skins and capes with elytra. However, they are needed for testing, In this case, we can only draw them on ourselves.

But on the other hand, not only are these textures for testing, but also give people a first impression, especially to those who are hesitating about which library to use. So a nice first glance is also important.

I have sent messages to several skin authors to request permissions. Once they agree, we can use their works in this repository.

**Comment by yushijinhun** [comment]
Implemented in #14.

**Comment by yushijinhun** [comment]
Reopen this issue to track further works.

- [ ] UI rework. 
      See https://github.com/to2mbn/skinview3d/pull/13#pullrequestreview-95665711.
- [ ] Request permissions from texture authors, drop unauthorized textures.
      The textures we are permitted to use are here: [`yushijinhun:example-texture`](https://github.com/yushijinhun/skinview3d/tree/example-texture/docs/examples/textures)
