### ISSUE TITLE
How to get rid of weird jagged lines and weird white dots on character without adding a background and turning off alpha

### ISSUE THREAD

**Issue by withdrew** [bs-community/skinview3d#92]
title
![57KhnBHV1](https://user-images.githubusercontent.com/52789876/130324274-a31af96f-598d-4aac-bca8-4606d2359286.png)

**Comment by withdrew** [comment]
happens even when i turn on FXAA

**Comment by withdrew** [comment]
i also have transparent background

**Comment by yushijinhun** [comment]
Please read the [Anti-aliasing section in readme](https://github.com/bs-community/skinview3d#anti-aliasing). Make sure you are using `FXAASkinViewer` and have specified an opaque background.
