### ISSUE TITLE
Is there anyway too fix this?

### ISSUE THREAD

**Issue by withdrew** [bs-community/skinview3d#93]
I've been trying to solve this problem for a couple weeks. The problem has to due with the skins background being white so it thinks the second layer is white but in game it isn't. I'm trying to make it as accurate as possible to the real game so any help would be great!
![d6de7d886b65ce9d (1)](https://user-images.githubusercontent.com/52789876/132104649-b266417d-25a4-4557-8a10-412da394e9ed.png)
![bob](https://user-images.githubusercontent.com/52789876/132104671-e85963ef-fec1-488f-83c2-cfe49b6db6cc.PNG)
![2021-09-04_14 01 09](https://user-images.githubusercontent.com/52789876/132104659-629bddb2-b3e6-401d-b933-735d26fa82d0.png)

**Comment by yushijinhun** [comment]
The skin you provided can't be displayed properly in game, so this might not be skinview3d's problem.

![image](https://user-images.githubusercontent.com/8373027/132269885-e5f212fd-e511-4de8-b848-5be784e106f5.png)

**Comment by withdrew** [comment]
hmm weird that doesn’t happen to me

**Comment by yushijinhun** [comment]
This problem occurs in Minecraft 1.9 and above.

**Comment by yushijinhun** [comment]
Fixed in v2.0.3.
