### ISSUE TITLE
Is there a way to detect when skinview3d THREE.js context gets restored after being lost?

### ISSUE THREAD

**Issue by withdrew** [bs-community/skinview3d#94]
title ^

**Comment by yushijinhun** [comment]
Take a look at https://github.com/bs-community/skinview3d/commit/7e3c0025e394a1f782e8255518c97e93d8ac00e3.

Now the animation will pause when the context gets lost, until it's restored.

**Comment by withdrew** [comment]
If the FXAA skinViewer loses context with a set background will the background have to be reset on this new update?

**Comment by withdrew** [comment]
Cus I have a set background but before this update when it got restored the background was turned back to the default which was black.

**Comment by yushijinhun** [comment]
I've added a `background` property to solve this problem (https://github.com/bs-community/skinview3d/commit/ff510a9ad0ba3a78c2361adbb4a3979eeb901021). Please try `skinViewer.background = ...`.

**Comment by withdrew** [comment]
Ok ty!

**Comment by withdrew** [comment]
Hey, is there anyway to manually cause a loss of context? Also to build it I had to revert the "@types/three" dependency to the last update so that might be a bug.

**Comment by withdrew** [comment]
pretty much I had to change "@types/three": "^0.131.1" back to "@types/three": "^0.131.0".

**Comment by withdrew** [comment]
Figured out how to manually cause context loss.

**Comment by yushijinhun** [comment]
> Hey, is there anyway to manually cause a loss of context?

```js
skinViewer.renderer.forceContextLoss();
```

**Comment by withdrew** [comment]
kk ty

**Comment by withdrew** [comment]
also the version thing i can't tell if it's just my end or not

**Comment by yushijinhun** [comment]
> Also to build it I had to revert the "@types/three" dependency to the last update so that might be a bug.

I didn't see anything wrong. The CI build succeeded and has been deployed to https://bs-community.github.io/skinview3d/.

**Comment by withdrew** [comment]
hmm weird

**Comment by withdrew** [comment]
I got this error `Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)`.

**Comment by withdrew** [comment]
might've done something wrong.

**Comment by withdrew** [comment]
I got it working!
