### ISSUE TITLE
LabyMod cape textures don't map onto cape model correctly

### ISSUE THREAD

**Issue by bribes** [bs-community/skinview3d#95]
I know this can be fixed by cropping the texture client-side but I am wondering if this can be added to sv3d itself.
Example Textures that don't map correctly:
- https://api.gapple.pw/cors/labymod/cape/fbc2dc1843cb438ab4e666dbad0e9e8c (IGN: bb)
- https://api.gapple.pw/cors/labymod/cape/a1bc77a1-a243-42d2-9ada-5684756a358c (IGN: 8)
- https://api.gapple.pw/cors/labymod/cape/8e176c5a-c26d-4c14-8efe-77b598b8b3ea (IGN: Skeppy)

Example of it not loading correctly:
![bb](https://user-images.githubusercontent.com/52789876/134773661-fb162229-04d2-49c5-83ff-29247cf8bcab.png)
![8](https://user-images.githubusercontent.com/52789876/134773666-42d2b5c7-4044-47f9-915e-8b26029c0103.png)

Example of what its suppose to look like:
![bb2](https://user-images.githubusercontent.com/52789876/134773715-a9b4214d-5f49-48b0-a62f-1edeeaa66819.PNG)
![82](https://user-images.githubusercontent.com/52789876/134773717-8e85341e-3a1b-4a5c-a32f-4d30a8dbf4fb.PNG)

**Comment by Hacksore** [comment]
As of now, I think the only supported cape sizes are:

`64x32`, `22x17`, and `46x22`

Source: https://github.com/bs-community/skinview-utils/blob/74fc0b02f8127a052cd8423da392b8570898ab5b/src/process.ts#L157

Demo: https://codesandbox.io/s/skinview3d-bad-cape-size-f1fcb?file=/src/index.js

**Comment by withdrew** [comment]
Hmm, I hope they add more support then. If possible of course.

**Comment by bribes** [comment]
Is there any timeline to when more cape sizes will be supported?

**Comment by bribes** [comment]
As of now I have to down size my capes to 46x22 to avoid errors.

**Comment by yushijinhun** [comment]
@bribes Does LabyMod have any documentation on its cape format? I found that [LabyMod Cloaks on its website](https://laby.net/cloaks) are all 22x17 in size.

**Comment by bribes** [comment]
> @bribes Does LabyMod have any documentation on its cape format? I found that [LabyMod Cloaks on its website](https://laby.net/cloaks) are all 22x17 in size.

Oh it’s seems like they actually resize and compress the files down to 22x17 after uploading.
